(() => {
  const q = s => document.querySelector(s);
  const fields = ['character','universe','controller','engine','authority-note','source-note','description','invariants','variations','prohibited','anatomy','palette','costume','equipment','movement','brief-type','intensity','scene','canon-status','commercial-status','reviewer','decision-note'];
  const checks = ['identity','anatomy','costume','provenance'];
  let images = [], candidate = null, currentId = '', brief = '';

  const status = (message, kind='') => { const el=q('#vs-status'); el.textContent=message; el.className=`vs-status ${kind}`; };
  const value = name => q(`#vs-${name}`)?.value?.trim() || '';
  const setValue = (name, val='') => { const el=q(`#vs-${name}`); if(el) el.value=val; };
  const stamp = () => new Date().toISOString();
  const makeId = () => crypto.randomUUID ? crypto.randomUUID() : `visual-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const safeName = text => (text || 'untitled').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();
  const readDataUrl = file => new Promise((resolve,reject)=>{ const r=new FileReader(); r.onload=()=>resolve(r.result); r.onerror=reject; r.readAsDataURL(file); });
  const digest = async file => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('');
  const download = (name,text,type='application/json') => { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),500); };

  const db = () => new Promise((resolve,reject)=>{ const req=indexedDB.open('epu-visual-studio',1); req.onupgradeneeded=()=>req.result.createObjectStore('records',{keyPath:'id'}); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); });
  const allRecords = async () => new Promise(async(resolve,reject)=>{ const d=await db(), req=d.transaction('records').objectStore('records').getAll(); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); });
  const putRecord = async rec => new Promise(async(resolve,reject)=>{ const d=await db(), req=d.transaction('records','readwrite').objectStore('records').put(rec); req.onsuccess=resolve; req.onerror=()=>reject(req.error); });
  const getRecord = async key => new Promise(async(resolve,reject)=>{ const d=await db(), req=d.transaction('records').objectStore('records').get(key); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); });
  const removeRecord = async key => new Promise(async(resolve,reject)=>{ const d=await db(), req=d.transaction('records','readwrite').objectStore('records').delete(key); req.onsuccess=resolve; req.onerror=()=>reject(req.error); });

  function gather(){
    const values={}; fields.forEach(n=>values[n]=value(n));
    const review={}; checks.forEach(n=>review[n]=q(`#vs-check-${n}`).checked);
    return {schema:'epu.visual-identity.v0.1',id:currentId||makeId(),createdAt:stamp(),updatedAt:stamp(),values,review,conceptImages:images,candidate,generatedBrief:brief,renderer:{adapter:'MANUAL_EXPORT',connected:false,target:'replaceable_adapter'},claims:['MOMMA_ADVISORY_ONLY','HUMAN_CANON_APPROVAL_REQUIRED','VISUAL_MATCH_NOT_OWNERSHIP','COMMERCIAL_CLEARANCE_SEPARATE','LOCAL_DEVICE_ONLY','RENDERER_NOT_CONNECTED']};
  }
  function fill(rec){
    currentId=rec.id||makeId(); fields.forEach(n=>setValue(n,rec.values?.[n]||'')); checks.forEach(n=>q(`#vs-check-${n}`).checked=!!rec.review?.[n]); images=rec.conceptImages||[]; candidate=rec.candidate||null; brief=rec.generatedBrief||''; q('#vs-brief-output').textContent=brief||'The generated brief will appear here.'; renderImages(); renderCandidate();
  }
  async function refreshList(selected=currentId){
    const list=q('#vs-record-list'), recs=await allRecords(); list.innerHTML='<option value="">New unsaved record</option>'; recs.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).forEach(r=>{ const o=document.createElement('option'); o.value=r.id; o.textContent=`${r.values?.character||'Untitled'} · ${r.values?.universe||'Unassigned'}`; list.append(o); }); list.value=selected||'';
  }
  function renderReadiness(){
    let panel=q('#vs-readiness'); if(!panel){panel=document.createElement('div');panel.id='vs-readiness';panel.className='vs-readiness';q('#vs-gallery').after(panel);}
    const anchor=images.find(img=>img.role==='identity_anchor'&&img.creatorConfirmed), basics=value('character')&&value('controller')&&value('authority-note')&&value('invariants');
    const ready=!!anchor&&!!basics; panel.className=`vs-readiness ${ready?'ready':''}`; panel.innerHTML=ready?`<b>Identity lock ready for human review</b><p>${anchor.name} is the creator-confirmed face and silhouette anchor. Supporting references cannot override it.</p>`:'<b>Visual lock not ready</b><p>Name the creator and authority, define identity invariants, then classify one image as an Identity anchor and confirm it. Other images may teach costume, anatomy, movement, environment, or mood without redefining the face.</p>';
  }
  function renderImages(){
    const box=q('#vs-gallery'); box.innerHTML=''; if(!images.length){box.innerHTML='<p class="muted">No concept images registered.</p>';renderReadiness();return;}
    images.forEach((img,i)=>{ const card=document.createElement('div'); card.className='vs-thumb'; const pic=document.createElement('img'); pic.src=img.dataUrl; pic.alt=img.name; const p=document.createElement('p'); p.textContent=`${img.name}\nSHA-256 ${img.sha256.slice(0,12)}…`; const role=document.createElement('select'); role.setAttribute('aria-label',`Reference role for ${img.name}`); [['unclassified','Unclassified'],['identity_anchor','Identity anchor'],['costume','Costume'],['anatomy','Anatomy / proportion'],['movement','Movement / pose'],['environment','Environment / scale'],['mood','Mood / lighting'],['exclude','Exclude from briefs']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;role.append(o);});role.value=img.role||'unclassified';role.onchange=()=>{img.role=role.value;if(img.role!=='identity_anchor')img.creatorConfirmed=false;renderImages();}; const confirm=document.createElement('label');confirm.className='vs-anchor-check';confirm.innerHTML='<input type="checkbox"> Creator confirms identity';const cb=confirm.querySelector('input');cb.checked=!!img.creatorConfirmed;cb.disabled=role.value!=='identity_anchor';cb.onchange=()=>{img.creatorConfirmed=cb.checked;renderReadiness();}; const b=document.createElement('button'); b.type='button'; b.textContent='×'; b.title='Remove image'; b.onclick=()=>{images.splice(i,1);renderImages();status('Concept image removed. Save the record to keep this change.');}; card.append(pic,p,role,confirm,b); box.append(card); }); renderReadiness();
  }
  function renderCandidate(){ const box=q('#vs-candidate-preview'); box.innerHTML=''; if(!candidate){box.innerHTML='<p class="muted">No candidate under review.</p>';return;} const img=document.createElement('img');img.src=candidate.dataUrl;img.alt=candidate.name;box.append(img); }
  function reset(){ currentId=''; images=[]; candidate=null; brief=''; fields.forEach(n=>setValue(n,'')); setValue('universe','Epos Paradox'); setValue('brief-type','Character profile'); setValue('canon-status','Concept only'); setValue('commercial-status','Internal concept — not for sale'); checks.forEach(n=>q(`#vs-check-${n}`).checked=false); renderImages();renderCandidate();q('#vs-brief-output').textContent='The generated brief will appear here.';q('#vs-record-list').value='';status('Fresh workspace ready. Nothing was deleted.'); }
  function buildBrief(){
    if(!value('character')){status('Name the character or subject before building a brief.','error');return;}
    const references=images.filter(x=>x.role!=='exclude').map(x=>`${x.creatorConfirmed?'CREATOR-CONFIRMED ':''}${(x.role||'unclassified').replaceAll('_',' ')} — ${x.name} — SHA-256 ${x.sha256}`).join('\n')||'No visual references attached. Do not infer a locked appearance.';
    brief=['MOMMA CREATIVE — GOVERNED VISUAL BRIEF',`Subject: ${value('character')}`,`Domain: ${value('universe')}`,`Controlling creator: ${value('controller')||'NOT RECORDED — do not infer authority'}`,'',`Requested deliverable: ${value('brief-type')}`,`Scene instruction: ${value('scene')||'Not specified'}`,`Tone / intensity: ${value('intensity')||'Not specified'}`,'',`Character truth: ${value('description')||'Not supplied'}`,`Identity invariants: ${value('invariants')||'Creator definition pending — do not invent locked traits'}`,`Permitted variations: ${value('variations')||'None documented'}`,`Prohibited drift: ${value('prohibited')||'None documented'}`,'',`Anatomy and geometry: ${value('anatomy')||'Use observed, functional anatomy and believable weight'}`,`Palette and materials: ${value('palette')||'Not specified'}`,`Costume language: ${value('costume')||'Not specified'}`,`Equipment / symbols: ${value('equipment')||'Not specified'}`,`Movement and expression: ${value('movement')||'Not specified'}`,'','GOVERNED VISUAL REFERENCES',references,'Identity anchors govern face and silhouette. Supporting references govern only their named role and cannot silently redesign identity.','','METHOD — LEONARDO AS FOUNDATIONAL TEACHER 001','Observe, measure, deconstruct, understand, reconstruct, test and refine. Use anatomy, geometry, light and function. Do not imitate a Renaissance surface style.','',`REFERENCE PROVENANCE: ${value('engine')||'Source engine or artist not recorded'}. ${value('source-note')||'No further source note.'}`,`AUTHORITY BOUNDARY: ${value('authority-note')||'Authority not documented. Treat output as an unapproved concept.'}`,'','MANDATORY DISPOSITION','The renderer produces a candidate only. MOMMA may compare and advise. A documented human must decide canon. Visual similarity does not determine ownership. Commercial clearance is separate.'].join('\n');
    q('#vs-brief-output').textContent=brief; status('Governed art brief built. Review it before sending it to any renderer.','good');
  }

  q('#vs-concepts').addEventListener('change',async e=>{ for(const file of [...e.target.files]){ if(images.length>=8){status('Eight-image concept limit reached.','error');break;} if(file.size>15*1024*1024){status(`${file.name} exceeds 15 MB and was skipped.`,'error');continue;} images.push({name:file.name,type:file.type,size:file.size,sha256:await digest(file),dataUrl:await readDataUrl(file),registeredAt:stamp(),sourceEngine:value('engine')||'not recorded',role:'unclassified',creatorConfirmed:false}); } renderImages(); e.target.value=''; status(`${images.length} concept image${images.length===1?'':'s'} registered. Classify what each image is allowed to teach MOMMA.`,'good'); });
  q('#vs-candidate').addEventListener('change',async e=>{ const file=e.target.files[0]; if(!file)return; if(file.size>15*1024*1024){status('Candidate exceeds 15 MB.','error');return;} candidate={name:file.name,type:file.type,size:file.size,sha256:await digest(file),dataUrl:await readDataUrl(file),registeredAt:stamp()}; renderCandidate(); e.target.value=''; status('Candidate attached for human review. No approval was inferred.','good'); });
  q('#vs-save').onclick=async()=>{ if(!value('character')){status('Name the character or subject before saving.','error');return;} const anchor=images.some(x=>x.role==='identity_anchor'&&x.creatorConfirmed); if(value('canon-status')==='Approved'&&(!value('reviewer')||!value('authority-note')||!anchor)){status('Approved status requires a named human reviewer, an authority note, and a creator-confirmed identity anchor.','error');return;} const rec=gather(); if(currentId){const old=await getRecord(currentId);rec.createdAt=old?.createdAt||rec.createdAt;} currentId=rec.id; await putRecord(rec); await refreshList(); status(`Saved ${value('character')} on this device.`,'good'); };
  q('#vs-load').onclick=async()=>{ const key=q('#vs-record-list').value;if(!key){status('Choose a saved record first.','error');return;} const rec=await getRecord(key);fill(rec);status(`Opened ${rec.values?.character||'visual record'}.`,'good'); };
  q('#vs-new').onclick=reset;
  q('#vs-delete').onclick=async()=>{ if(!currentId){status('No saved record is open.','error');return;} if(!confirm(`Delete the saved local record for ${value('character')||'this subject'}? Export first if it must be preserved.`))return; await removeRecord(currentId);reset();await refreshList();status('Saved record deleted from this device.','good'); };
  q('#vs-build-brief').onclick=buildBrief;
  q('#vs-copy-brief').onclick=async()=>{if(!brief)buildBrief();if(brief){await navigator.clipboard.writeText(brief);status('Brief copied.','good');}};
  q('#vs-download-brief').onclick=()=>{if(!brief)buildBrief();if(brief)download(`${safeName(value('character'))}-visual-brief.json`,JSON.stringify({schema:'epu.visual-brief.v0.1',character:value('character'),brief,createdAt:stamp(),claims:['MOMMA_ADVISORY_ONLY','HUMAN_CANON_APPROVAL_REQUIRED']},null,2));};
  q('#vs-export').onclick=()=>{ const rec=gather(); if(!value('character')){status('Name the subject before export.','error');return;} download(`${safeName(value('character'))}.epu-visual-record.json`,JSON.stringify(rec,null,2));status('Portable visual package exported. Embedded images may make it large.','good'); };
  q('#vs-import').onclick=()=>q('#vs-import-file').click();
  q('#vs-import-file').onchange=async e=>{try{const parsed=JSON.parse(await e.target.files[0].text());if(parsed.schema!=='epu.visual-identity.v0.1')throw Error('Unsupported visual package schema.');fill(parsed);status('Visual package restored. Save it to add it to this device’s library.','good');}catch(err){status(`Import failed: ${err.message}`,'error');}e.target.value='';};
  q('#vs-demo').onclick=()=>{reset();setValue('character','Kiya Virelle');setValue('universe','Epos Paradox');setValue('controller','Sean Alan LaViscount');setValue('authority-note','Sean controls this demonstration record. Any additional creator or company rights must be documented before promotion or sale.');setValue('description','Keen-witted combatant whose physical intelligence and “fancy karate” carry an encounter against thirty-four combatants near the former Verrazzano Bridge. This is a working example, not a completed visual definition.');setValue('invariants','Creator definition pending. Preserve the same facial identity, silhouette, physical logic and emotional presence once established; do not treat a renderer’s first guess as canon.');setValue('variations','Camera, weather, pose, expression and scene damage may vary while identity remains stable.');setValue('prohibited','Generic superhero drift; impossible anatomy; arbitrary costume changes; borrowed franchise symbols; visual features presented as canon without creator review.');setValue('anatomy','Functional anatomy, stable balance, believable leverage and readable weight transfer under combat motion.');setValue('movement','Economical, intelligent and adaptive. Action should reveal decision-making rather than ornamental posing.');setValue('brief-type','Action scene');setValue('scene','Kiya survives and controls a chaotic confrontation near the former Verrazzano Bridge. Stage the action so her tactical awareness remains legible without glamorizing incoherent violence.');status('Kiya example loaded. Replace every placeholder with creator-defined truth before approval.','good'); };
  ['character','controller','authority-note','invariants'].forEach(n=>q(`#vs-${n}`).addEventListener('input',renderReadiness));
  refreshList().then(renderReadiness).catch(()=>status('Local visual library could not be opened in this browser.','error'));
})();
